import { beforeAll, afterAll, it, expect } from 'vitest';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { MongoClient } from 'mongodb';
import { MongoStore } from '../../server/store';
import { initialState } from '../../server/model';
import { setup, register, complete } from '../helpers';
let mongo:MongoMemoryServer,client:MongoClient;
beforeAll(async()=>{mongo=await MongoMemoryServer.create();client=await new MongoClient(mongo.getUri()).connect();});
afterAll(async()=>{await client?.close();await mongo?.stop();});
it('Mongo concurrent retry starts, answers and restarts persist once across service instances',async()=>{
 const make=()=>setup(new MongoStore(client,'retry_test',initialState())).service;
 const service=make(),a=await register(service),date=a.view.date;
 await complete(service,a.token,false);
 const before=await service.store.read(),instances=Array.from({length:4},make);
 const starts=await Promise.all(instances.map(s=>s.execute(a.token,{action:'startRetry',date})));
 const id=starts[0].reply.view.retry!.id;
 expect(new Set(starts.map(r=>r.reply.view.retry!.id)).size).toBe(1);
 const items=before.lessons[date].items;
 const cmd={action:'answer' as const,date,target:'retry' as const,sessionId:id,itemId:items[0].id,input:items[0].answers[0]};
 const answers=await Promise.all(instances.map(s=>s.execute(a.token,cmd)));
 for(const result of answers)expect(result.reply.feedback).toEqual(answers[0].reply.feedback);
 expect((await make().view(a.token)).retry!.answers).toHaveLength(1);
 for(const item of items.slice(1))await service.execute(a.token,{...cmd,itemId:item.id,input:item.answers[0]});
 const restarts=await Promise.all(instances.map(s=>s.execute(a.token,{action:'startRetry',date,previousSessionId:id})));
 expect(new Set(restarts.map(r=>r.reply.view.retry!.id)).size).toBe(1);
 expect(restarts[0].reply.view.retry!.id).not.toBe(id);
 const restored=await make().view(a.token),after=await service.store.read();
 expect(restored.retry!.answers).toHaveLength(0);
 expect(after.users[a.id].reviews).toEqual(before.users[a.id].reviews);
 expect(restored.progress!.answers).toEqual(before.users[a.id].progress[date].answers);
 expect(restored.progress!.completedAt).toBe(before.users[a.id].progress[date].completedAt);
});
