import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, BookOpen, CheckCircle2, ChevronRight, Clock3, Leaf, RefreshCw } from 'lucide-react';
import { useApp } from './state';
import { Artwork, ErrorNote } from './components';
export function Home(){
 const{view,run}=useApp(),navigate=useNavigate();const [busy,setBusy]=useState(false),[error,setError]=useState('');const p=view.progress!,items=view.lesson!.items;
 const open=async(index:number)=>{setBusy(true);setError('');try{await run({action:'card',date:view.date,index});navigate('/learn');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><div className="page-heading"><div><div className="eyebrow">YOUR DAILY ENGLISH</div><h1>{view.user?.name}님, 오늘도 한 걸음.</h1><p className="muted">작은 표현들이 모여, 더 넓은 일상이 돼요.</p></div><span className="day-badge"><span>DAY</span>{String((view.stats?.completedDays||0)+(p.completedAt?0:1)).padStart(2,'0')}</span></div><section className="hero"><div><span className="pill"><Leaf size={14}/> 오늘의 작은 목표</span><h2>{p.completedAt?<>오늘의 열 개,<br/>마음에 담았어요.</>:<>하루 열 개면 충분해요.<br/>오늘의 영어를 만나 보세요.</>}</h2><p>{view.lesson!.topic}</p><button className="button primary" onClick={()=>navigate(p.completedAt?'/result':p.cardsDone?'/quiz':'/learn')}>{p.completedAt?'오늘의 결과 보기':p.cardsDone||p.card?'이어서 학습하기':'오늘의 학습 시작'}<ArrowRight size={18}/></button><div className="hero-meta"><span><Clock3 size={14}/> 5~10분</span><span><BookOpen size={14}/> 10개 표현</span></div></div><Artwork/></section><div className="section-heading"><div><h2>오늘의 표현 <span className="number-tag">10</span></h2><p>단어부터 구동사까지, 일상에서 바로 쓰는 영어.</p></div><span className="completion">{p.answers.length}/10 완료</span></div><ErrorNote message={error}/><div className="word-grid">{items.map((item,index)=><button className="word-row" disabled={busy} key={item.id} onClick={()=>void open(index)}><span className="word-number">{String(index+1).padStart(2,'0')}</span><span className="word-info"><strong>{item.expression}</strong><span>{item.meaning}</span></span><span className="kind">{item.kind}</span>{p.answers.some(a=>a.itemId===item.id)?<CheckCircle2 size={18} className="green"/>:<ChevronRight size={17} className="muted"/>}</button>)}</div><section className="review-banner"><div className="icon-circle"><RefreshCw size={22}/></div><div><h3>기억은 다시 만날 때 단단해져요.</h3><p>{view.review?.due?view.review.due+'개의 표현이 다시 만날 날을 기다리고 있어요.':'배운 표현은 시간이 지나면 복습에 모여요.'}</p></div><button className="text-button" onClick={()=>navigate('/review')}>선택 복습<ArrowRight size={17}/></button></section></>;
}
