import { useState } from 'react';
import { ArrowRight, Check, Lightbulb, X } from 'lucide-react';
import { feedbackTranslation, type Attempt, type Question } from '../shared/contracts';
export function QuizPanel({question,number,total,onAnswer,onHint,onFinish}:{question?:Question;number:number;total:number;onAnswer:(value:string)=>Promise<Attempt>;onHint:()=>Promise<void>;onFinish:()=>void}){
 const [input,setInput]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState<Attempt>();
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!input.trim()||busy)return;setBusy(true);setError('');try{setFeedback(await onAnswer(input));}catch(e){setError(e instanceof Error?e.message:'저장하지 못했어요. 다시 시도해 주세요.');}finally{setBusy(false);}};
 const hint=async()=>{setBusy(true);setError('');try{await onHint();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className="study-card quiz-card"><div className="eyebrow">RECALL IN CONTEXT <span>{Math.min(number+(feedback?0:1),total)} / {total}</span></div><h2>문장 속 빈칸을 채워 보세요.</h2><p className="muted">학습한 표현을 사용해 주세요. 여러 단어도 괜찮아요.</p>
 {feedback?<><div className={'feedback '+(feedback.correct?'correct':'incorrect')}><div className="feedback-title">{feedback.correct?<Check size={22}/>:<X size={22}/>} {feedback.correct?'잘 기억하고 있어요!':'한 번 더 익혀 두세요.'}</div><strong>{feedback.expected}</strong><p>{feedback.sentence}</p><small>{feedbackTranslation(feedback.translation)}</small>{!feedback.correct&&<p className="your-answer">내 답: {feedback.input}</p>}</div><button className="button primary wide" onClick={()=>{setFeedback(undefined);setInput('');if(!question)onFinish();}}>{question?'다음 문제':'결과 보기'}<ArrowRight size={18}/></button></>:
 question?<form onSubmit={submit}><div className="sentence">{question.sentence.split('___')[0]}<span className="blank">•••</span>{question.sentence.split('___')[1]}</div><label className="field-label" htmlFor="answer">영어 표현</label><input id="answer" autoComplete="off" autoCapitalize="none" spellCheck={false} placeholder="기억나는 표현을 적어 주세요" value={input} onChange={e=>setInput(e.target.value)} disabled={busy} autoFocus maxLength={120}/>
 {question.hint?<div className="hint"><Lightbulb size={16}/>{question.hint}</div>:<button type="button" className="text-button hint-button" onClick={hint} disabled={busy}><Lightbulb size={16}/> 뜻 힌트 보기</button>}{error&&<div role="alert" className="error">{error}</div>}<button className="button primary wide" disabled={busy||!input.trim()}>{busy?'저장하는 중…':'정답 확인'}<ArrowRight size={18}/></button></form>:<><p>준비된 문제를 모두 풀었어요.</p><button className="button primary wide" onClick={onFinish}>결과 보기<ArrowRight size={18}/></button></>}</section>;
}
